hash-format = "sha256"

[[files]]
file = "mods/antighost.toml"
hash = "f82bd50454622bf85741c23664a0d7fa95bbc01e02cd15e608f237b73f249d1a"
metafile = true

[[files]]
file = "mods/architectury-fabric.toml"
hash = "4c43ae92b14cd3e60ff078ce4cf8db12153edf9c2e9fb40f63994f84c034cc9f"
metafile = true

[[files]]
file = "mods/better-enchanted-books.toml"
hash = "7f6bf37922b4a418427eeea23457b654f3b61b30dbb98d1d051452ef4395ce7b"
metafile = true

[[files]]
file = "mods/blur-fabric.toml"
hash = "fbb12ba771ff025ae7503ff59b01e6bc416dc055fe978f75a3db067b13c85fac"
metafile = true

[[files]]
file = "mods/clear-skies.toml"
hash = "1f4444c6a94e97e91e591cd5ea28b3146d6611ac0af3db4b36486df549e7edb3"
metafile = true

[[files]]
file = "mods/clickthrough.toml"
hash = "51c5193b4b036db0512e7f0933fb97973c88d48c43e734c7314c68998a356104"
metafile = true

[[files]]
file = "mods/cloth-config.toml"
hash = "0a52ac326bf7a04031a8b9b186ffd26c2990012866d077445afc207744285366"
metafile = true

[[files]]
file = "mods/command-macros.toml"
hash = "895d4da3a181a263be4107364f082582e8759ce2295e6bf8c8369a033fed9424"
metafile = true

[[files]]
file = "mods/craftpresence.toml"
hash = "2439514e1c20fb0f2593358e249f987c590e4a551ffe634aea0d09b17287ddc0"
metafile = true

[[files]]
file = "mods/critical-flight-details.toml"
hash = "fd1b2c2aad80a2ddbd7e1ce903132afca0bf1b3ec484662e55ed53e026e025e8"
metafile = true

[[files]]
file = "mods/critical-orientation.toml"
hash = "8cc0f2e6ea67d26471df5de09ba2ca53a9a72742a649535fc0dbf594859e7997"
metafile = true

[[files]]
file = "mods/durabilityviewer.toml"
hash = "3e07ea859745e4ff08cc7ee2f6ed7b5fb47d60bc761d52309011e168d8a7d2cf"
metafile = true

[[files]]
file = "mods/easiercrafting.toml"
hash = "d7d4dc938fb8f5f2262b8c4888fa34ccd98ad064ed8968c7b58b31149e3d1f69"
metafile = true

[[files]]
file = "mods/emcutils.toml"
hash = "d7c5173c1ad075591dec45d1051991571830729f4e98cba23c21b080ad1f2b71"
metafile = true

[[files]]
file = "mods/fabric-api.toml"
hash = "d09e7bc5459ed809a3c32cdeea1ef8f71f2df4b19e147da9a6f60765c99da16e"
metafile = true

[[files]]
file = "mods/flighthelper.toml"
hash = "c5689310f373dd2c5bd339c6904d72365c3e6ffdf140df7e2344622ba5176e72"
metafile = true

[[files]]
file = "mods/hwyla.toml"
hash = "e37316132d574a8472b50140adf0816b2f2b7cacf7f391ea6fe4b8be7cbe4b73"
metafile = true

[[files]]
file = "mods/hydrogen.toml"
hash = "153cda3c6d61ae9b32117fe5315ee40a0bd561b7292d9a5927773a368b52c254"
metafile = true

[[files]]
file = "mods/inventory-profiles.toml"
hash = "2c15341ca11e195b5b5d7923d7c33545ae921f2f91bc3c9e16278aefa1240b85"
metafile = true

[[files]]
file = "mods/item-scroller.toml"
hash = "880eb609329689d5dcce7aa094a09080826fa629d18dc4f92a3b74b284b50f8a"
metafile = true

[[files]]
file = "mods/krypton.toml"
hash = "2148d404b7cf3a72a469be3433272f13218a98d0cc1af4b9abb2886bbc7848c3"
metafile = true

[[files]]
file = "mods/light-overlay.toml"
hash = "b1d40c47ce5bb0ddde45742c0d6c41d4dab5866de80baecf2003ec070eb93e6d"
metafile = true

[[files]]
file = "mods/litematica.toml"
hash = "dfb05ccf6d0a0dcc6d2c15a462ab01275ced75dbff3bd853008ad10ddb307d4b"
metafile = true

[[files]]
file = "mods/lithium.toml"
hash = "6066fcc10464ca625efe86c05c8414acc2fe6b69c3fabc05b61eb7ddf33090de"
metafile = true

[[files]]
file = "mods/low-fire.toml"
hash = "637e553a734ecbb876166f06f05ad6ecc75b1577ac21d38c10b1cde3e91cfaa5"
metafile = true

[[files]]
file = "mods/malilib.toml"
hash = "35cdd7a1c9b2dd09d458773be1fef94eaca2138b6a96f218921b2deaa0380c4e"
metafile = true

[[files]]
file = "mods/minemenufabric.toml"
hash = "04807434817c0236addfacc1062a4bc4ef7fdebd9d0686bdf719220a56386746"
metafile = true

[[files]]
file = "mods/minihud.toml"
hash = "f7a18e0438a168d0bdd2035f0828e2e5d86626d6144a8788f07f13dabd20b487"
metafile = true

[[files]]
file = "mods/modmenu.toml"
hash = "c2dc58ad1ce065d73a250283bf1849cf07c1e211892ccbb4d943b7c59c79b22c"
metafile = true

[[files]]
file = "mods/modupdater.toml"
hash = "2cbde04987e29550cf7d9436667ecc789dfb9d17779bf2aec458efb19fcd9894"
metafile = true

[[files]]
file = "mods/nmuk.toml"
hash = "ef61cd24dec2ab42fe8eadb4b3034cd730b379721f6ef736625de7efb85ef765"
metafile = true

[[files]]
file = "mods/no-strip.toml"
hash = "024c61ce6ab3978bbeb472ec785fb36592cda40966f1df40a2324e2cabf7b544"
metafile = true

[[files]]
file = "mods/nofog.toml"
hash = "60bd58ebc4b23339786a122d28a15370acb14cb389fabec3ef8ba00dd5c4396f"
metafile = true

[[files]]
file = "mods/not-enough-crashes.toml"
hash = "48801db07e7f0352c9a155aa236c01a48b85e638424d41c89a02a7cdcd1266ad"
metafile = true

[[files]]
file = "mods/optifabric.toml"
hash = "825df8d42445f110f69991012e238dc3e311fa9f7fad02aae004b7dbe54a9c6e"
metafile = true

[[files]]
file = "mods/optifine.toml"
hash = "41c037eec5e7f43711c928b1d4660c995dbb0f4715d0b59f3d9670b2b061dd63"
metafile = true

[[files]]
file = "mods/phosphor.toml"
hash = "1e06139deec8b03ae4f0b471d9b8a04750dbacabd6f91391230caa86e2487104"
metafile = true

[[files]]
file = "mods/reauth-fabric.toml"
hash = "7e7440866874e0dd11fa64d3df8c8848b2c0d0464af0b74bd546ab654503510a"
metafile = true

[[files]]
file = "mods/shulkerboxtooltip.toml"
hash = "68027a1e55bff56cda351b453bd3a249138fde501b864a54f1c4b7bb8f57078a"
metafile = true

[[files]]
file = "mods/smooth-scrolling-everywhere-fabric.toml"
hash = "e3f3c5a10f9acb1ba30b80e00033b16b1fb565a14b6ca69f721efbb033abdba5"
metafile = true

[[files]]
file = "mods/torohealth-damage-indicators.toml"
hash = "4ab41d2e583913c1b59c811b406c3f2da63a1ba0fb0607a3db5810b14abc89bb"
metafile = true

[[files]]
file = "mods/worldedit.toml"
hash = "7165a0a85f4db8b2cb40a6540dfcb2e74c652a772cef1f239840c0c631038a3f"
metafile = true

[[files]]
file = "mods/worldeditcui.toml"
hash = "a9d9a9534aed7475428d7ce391f64ef110637fbca6778d9c3b73d20b8418fae7"
metafile = true

[[files]]
file = "mods/xaeros-minimap.toml"
hash = "fd1eebd209abf23c1c6b10d416601e89427a4f35d54fced566709abcf51e44b8"
metafile = true

[[files]]
file = "mods/xaeros-world-map.toml"
hash = "16b89188be0c590ef27497d8d7bd076eecfbec07576eb6746f3610de424c89f5"
metafile = true
