hash-format = "sha256"

[[files]]
file = "mods/amecs.toml"
hash = "e8eaae7f120b2a5e979a6d468b9eebc1334ce72341d9519e1a7dfaa9ff28e902"
metafile = true

[[files]]
file = "mods/antighost.toml"
hash = "9f0e322f805194c5634cdd88868199ba52abe25d79c216fff98a72789d992475"
metafile = true

[[files]]
file = "mods/audio-output.toml"
hash = "2b98e509b6d9a2bab0bb87bcde9df6e6cf5ab844953f0097f2cef922d331728f"
metafile = true

[[files]]
file = "mods/auth-me.toml"
hash = "4819af6e7d78be6fc3f8e22d5cf8dda7c051c862e3b2a01d3c4716f031446710"
metafile = true

[[files]]
file = "mods/better-enchanted-books.toml"
hash = "4362e3f53bbb83a932be2ec724f132502e5e6bf40b1ec95b300983c71cec1fc0"
metafile = true

[[files]]
file = "mods/blur-fabric.toml"
hash = "74f39c302b1f85b1ada3cd82e89298875fec9e323ddead7cb52e3740f30171bb"
metafile = true

[[files]]
file = "mods/clear-skies.toml"
hash = "d0e4644a0ed3cc7a5ba173e4979bff11fddf2ab8dbd65cf18ce65f862b034f4c"
metafile = true

[[files]]
file = "mods/clickthrough.toml"
hash = "fd01d03754dbdec0cadb3574a8326756d786939339764f278367e3213255b215"
metafile = true

[[files]]
file = "mods/cloth-config.toml"
hash = "94b98ae68382da3bf4f3bd3115319c75bc8e078ce856cee4040d2710b97ddead"
metafile = true

[[files]]
file = "mods/colored-lights.toml"
hash = "51f877738ccffedf0b6eb21ed74624eca265d297e0a258ab126f8b02b6bd15fe"
metafile = true

[[files]]
file = "mods/command-macros.toml"
hash = "a9eb46816dc3a2acbda7bf3152b574cab86576089627affef45557bd31aca804"
metafile = true

[[files]]
file = "mods/craftpresence.toml"
hash = "25c7469eed7fad7734cfe2221d66b592058ffe102d7aa47531a34954c54a54a0"
metafile = true

[[files]]
file = "mods/critical-flight-details.toml"
hash = "67643dcc9914dbf20d038ba6eea8c4bf6f1c2772f9d79db2fb73710e93cb0386"
metafile = true

[[files]]
file = "mods/critical-orientation.toml"
hash = "6fe6756ed0327189433f46fd0deca4517b198fc09766758079ce86d36250ad24"
metafile = true

[[files]]
file = "mods/ctm-fabric.toml"
hash = "948103cea686d9cf5a953b24205b753fd69a133aa304c768c26cc4fd99924076"
metafile = true

[[files]]
file = "mods/cull-leaves.toml"
hash = "73373969b6bc944d82bc8799cfbac796a7abdddfb348e661395d54f1340e9694"
metafile = true

[[files]]
file = "mods/deathlog.toml"
hash = "3cb61c5e66f85b77d56e4e20df1ed7f193504725b56e0ddabef7467319fe9a6f"
metafile = true

[[files]]
file = "mods/dont-clear-chat-history.toml"
hash = "069c79d189a26d846ef545b01911655158a6865e607287bb439371eeebac9adf"
metafile = true

[[files]]
file = "mods/durabilityviewer.toml"
hash = "bb96de2bb22da9b0c016893e4d3a2cb032c662256b39b83a7cfc2a0b7099f6e1"
metafile = true

[[files]]
file = "mods/dynamic-fps.toml"
hash = "de92736c9962081ec15ab83b884e9e7b858970a3d06f236c8d095197325458af"
metafile = true

[[files]]
file = "mods/easiercrafting.toml"
hash = "ba4bbdb92e56fc37a154cb9e24ac1860269d2b277a0537d458c39e01446b6b9a"
metafile = true

[[files]]
file = "mods/ebe.toml"
hash = "6c11ca8b1f4f3c9be04e5eb1ace4aac1cd6bdf8660f7ed5a7b0d0ff3a9e02842"
metafile = true

[[files]]
file = "mods/emcutils.toml"
hash = "315fdf1ad1deb0b0ffd4ffa63468c0773694fbbca8e89fd279e353835508fdee"
metafile = true

[[files]]
file = "mods/entityculling.toml"
hash = "ec2f5b3fe9418dc4de48912c216c7aa5ddc2f9092e0ed6e495a2afd2cce87536"
metafile = true

[[files]]
file = "mods/fabric-api.toml"
hash = "49bec4191d8ba299ec945acc812cb8ad6add90c16e659f25b040a6b329c4d59b"
metafile = true

[[files]]
file = "mods/fabrishot.toml"
hash = "42f6b01f10364d595bbc3915f5c88377164e058f961a3b7ceb2edf20582a41ea"
metafile = true

[[files]]
file = "mods/ferrite-core.toml"
hash = "868f81f9da3a432950f1bb0ae41cfccb5b70d6e4d945e2246628a47b04ffcc6f"
metafile = true

[[files]]
file = "mods/hudtweaks.toml"
hash = "75896b783d612e1e5789b069217f6328206bcc937d2a2ee3162fbdec7cd8b369"
metafile = true

[[files]]
file = "mods/hydrogen.toml"
hash = "8c567c4bdc98f31981a86b309d43b6352c64ca595005e6d2730a55ff641e77f7"
metafile = true

[[files]]
file = "mods/indium.toml"
hash = "743b3b7e1af583ae49e4781fe7651a08727115884067e73328a3db3abb52ed0f"
metafile = true

[[files]]
file = "mods/inspecio.toml"
hash = "1f646c78275b15ca0cb4e195dafc53d90769b0fa5575a46f1dfd2945f2becbb8"
metafile = true

[[files]]
file = "mods/inventory-profiles-next.toml"
hash = "67d803df4e8f94007ff9d419054f5f1451f4a0d73d23492e1e2a3aac038b29fb"
metafile = true

[[files]]
file = "mods/iris.toml"
hash = "f72799aa1233ca2d921ffc8c2d32990f8cbb1317b0ebeff489c8eb6a9e5c0092"
metafile = true

[[files]]
file = "mods/item-scroller.toml"
hash = "c59798f808a9a5306d6b907e1634e4ca9c67a8181c19e6d9d648b7496df243e2"
metafile = true

[[files]]
file = "mods/krypton.toml"
hash = "53c1497f1d36ff97918eecd378094c563c2cea25ada65b2d61524b6fbf775daa"
metafile = true

[[files]]
file = "mods/lambdabettergrass.toml"
hash = "89026a8d35dd040fc95b3f256bd98085ae91f4508302fbba6307f2dcfaf8c23f"
metafile = true

[[files]]
file = "mods/lambdynamiclights.toml"
hash = "6fea0a500639e66a61dc04f6a3a78d2eb943219a73d9efe817714d06141671eb"
metafile = true

[[files]]
file = "mods/lazydfu.toml"
hash = "da1b3ee71d9ed1f17da4c85ca3da39af3e49fcc5bb032689613c4e00fc587a40"
metafile = true

[[files]]
file = "mods/lightlevel.toml"
hash = "103fdf5afbc2caa5f008a75efc87f18ee3d5b5b045540c6ab10085b04a0a6c6f"
metafile = true

[[files]]
file = "mods/litematica.toml"
hash = "6f222cd260f4cc7a322e6e4ffd1e74649b630ec08e0fae0402a74970d9c2bf2e"
metafile = true

[[files]]
file = "mods/lithium.toml"
hash = "aadac356f42ec0990857fe8a3c07f04075a56c39d67bde0c75237489fbcbcd00"
metafile = true

[[files]]
file = "mods/low-fire.toml"
hash = "3c6eada0ef5f9c12a7c12592d635b5ae226927fdcbc1e048e11defac8d10e30e"
metafile = true

[[files]]
file = "mods/malilib.toml"
hash = "fe8e60e3917e13a3a5ea46b7402d8d35850829c669e8b97f3c869bf4ce6c21ad"
metafile = true

[[files]]
file = "mods/minihud.toml"
hash = "9731cbf2f3a2aa14cd3948a8caee970a6dc66fa84c1f0c10be5cc522fe2882ec"
metafile = true

[[files]]
file = "mods/modmenu.toml"
hash = "c32296d53c667681bc59834eb553cfd53030d60a248184b5569e3718af8807f5"
metafile = true

[[files]]
file = "mods/nbttooltip.toml"
hash = "3aed0d3a60bdf6b25f685ef3fb81eb99a3c4bc002256c972e6b43c92a4fb8317"
metafile = true

[[files]]
file = "mods/nmuk.toml"
hash = "ef8a6f681af3f2a800a4eb4e1cff78b8ba4f42762b5eff65b103957184016275"
metafile = true

[[files]]
file = "mods/no-strip.toml"
hash = "bc3b726ebcf2ed01dd18c8cb55746984c52443c3907a24ebfd9ca29fc48af5c8"
metafile = true

[[files]]
file = "mods/nofog.toml"
hash = "af771bd5e619c99fe4a9d53d2e30668356298b1e8475b4906c21e52441c72f7a"
metafile = true

[[files]]
file = "mods/notenoughcrashes.toml"
hash = "70d4e6f9a058ee58e87f3c6fef0ae7441fedda4f4004746d83dc0cc7373fb439"
metafile = true

[[files]]
file = "mods/ok-zoomer.toml"
hash = "a826b893ccf96de25429d13d470f5509ce6f998c2c6533c9c0567f8f982b01e0"
metafile = true

[[files]]
file = "mods/quilt-loading-screen.toml"
hash = "53a2a2604c0fad23019ff7722dca7d0e4bca97528865ae0eac1fcdf1b92a300e"
metafile = true

[[files]]
file = "mods/rebind-all-the-keys.toml"
hash = "3b814f557bf5f34dda723d82b8c493892d430b081ea7b723acb704af3e0061a4"
metafile = true

[[files]]
file = "mods/roughly-enough-items.toml"
hash = "fc7eb25a81c148c39d5cc081cf03e5402301c75c6cf04f70a1b3a9c6cd819b57"
metafile = true

[[files]]
file = "mods/shulkerboxtooltip.toml"
hash = "7d7e0bdae7f646b904e42210c4d32e7f974fac3b0019fe60e715faaf75a6998f"
metafile = true

[[files]]
file = "mods/shut-up-console.toml"
hash = "f506b31d66529652ca807fca0d3c073de017a7af046cba3e73a1d22b47a6be8f"
metafile = true

[[files]]
file = "mods/smooth-scrolling-everywhere-fabric.toml"
hash = "3c76f6dc31a39c5798a85d997883a4dd881a469a838b0cbff14499f393c9f477"
metafile = true

[[files]]
file = "mods/sodium.toml"
hash = "1568f85b32f431c39374ded6a5fe20044b37d5d6ca4c963cef6f0616d7c1cab2"
metafile = true

[[files]]
file = "mods/starlight.toml"
hash = "ee5f6ad60e486e22847ad71874e08bf77e4660a1ca9591367bf412882ced8475"
metafile = true

[[files]]
file = "mods/textweaks.toml"
hash = "44e404eb254c00b3048024943c79729ff56796f58c76b11776be07602ca183e0"
metafile = true

[[files]]
file = "mods/time-changer.toml"
hash = "b9cbf9ab4c86adefdd929b848a77ac847fef7ebb101270d7aa404b840a46aeee"
metafile = true

[[files]]
file = "mods/torohealth-damage-indicators.toml"
hash = "1ecfd5ca2d8ad6323372162e3f4416a122492a0819f4347a2972b263bdc2afee"
metafile = true

[[files]]
file = "mods/worldedit.toml"
hash = "479d2f8f1b07df980c088aa87fb8ea1972a8e3ab9a0284919e61fa7cd438d995"
metafile = true

[[files]]
file = "mods/worldeditcui.toml"
hash = "5a4fbed753e1e8e46146fba87b9168f18876c9d2b6dd81d85a1d0bdddaa2629c"
metafile = true

[[files]]
file = "mods/wthit.toml"
hash = "1511a6b8f2abce67ed32712880fc52d6eff29010bdd77089de4c0eac075dad99"
metafile = true

[[files]]
file = "mods/xaeros-minimap.toml"
hash = "b54419d960f2c2baf748ff3aecf7c8be8930ca20ea03d39581675ecc850d5e85"
metafile = true

[[files]]
file = "mods/xaeros-world-map.toml"
hash = "a0ed6899cf9e7574fe75a17b45ed86a5bd2be9ce9c5f9306c1494821648101f6"
metafile = true

[[files]]
file = "mods/yosbr.toml"
hash = "218b2b38862091f96e1db0ee7580c6f9cd5e8f008f88e4fe00016c6dea1065b3"
metafile = true
